import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { config } from '../config.js';
import { resolveActiveClaudeExecutable } from '../utils/resolve-claude-bin.js';

const SHIM_DIR = path.join(os.homedir(), '.claudegram');
const SHIM_PATH = path.join(SHIM_DIR, 'claude-via-ccr.sh');

let cachedShim: string | undefined;

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Generate (or refresh) the wrapper script that exports CCR env vars and
 * execs the real `claude` binary. Returning the path lets the SDK launch
 * `claude` with CCR redirection without ever mutating `process.env` in the
 * Claudegram process — keeping concurrent queries race-free.
 */
export function getCcrShimPath(): string {
  if (!config.CCR_ENABLED) {
    throw new Error('CCR is not enabled (set CCR_ENABLED=true)');
  }
  if (cachedShim && fs.existsSync(cachedShim)) {
    return cachedShim;
  }

  if (!fs.existsSync(SHIM_DIR)) {
    fs.mkdirSync(SHIM_DIR, { recursive: true, mode: 0o700 });
  }

  const realClaude = resolveActiveClaudeExecutable();
  const baseUrl = shellSingleQuote(config.CCR_BASE_URL);
  const authToken = shellSingleQuote(config.CCR_AUTH_TOKEN);
  const target = shellSingleQuote(realClaude);

  const script = `#!/bin/sh
# Auto-generated by Claudegram. Do not edit.
# Redirects the spawned claude CLI through a Claude Code Router proxy.
export ANTHROPIC_BASE_URL=${baseUrl}
export ANTHROPIC_AUTH_TOKEN=${authToken}
unset ANTHROPIC_API_KEY
exec ${target} "$@"
`;

  fs.writeFileSync(SHIM_PATH, script, { mode: 0o700 });
  cachedShim = SHIM_PATH;
  return SHIM_PATH;
}

/** Force-regenerate the shim on next call (e.g. after config change). */
export function invalidateCcrShim(): void {
  cachedShim = undefined;
}
